# Generated by Django 3.2.6 on 2021-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbanil',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
