# Generated by Django 3.2.6 on 2021-08-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_thumbanil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbanil',
            new_name='thumbnail',
        ),
    ]
